name: Abhishek2
on:
  push:
    branches: [ "main" ]
  pull_request :
    branches: ["main"]
  
  #workflow_dispatch:

jobs:
  build1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo window-successful.

  build2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo linux-successful.

 
